### ISSUE TITLE
PHP Track Courses to be completed

### ISSUE THREAD

**Issue by msankho** [msankho/Treehouse#2]

**Comment by msankho** [comment]
## TODO
*Courses left to complete the Treehouse PHP track*

* [x] Designing interfaces in PHP
* [x] Practice hashing passwords in PHP
* [x] Practice including PHP with HTML
* [ ] Extending object oriented PHP


:tada: :ok_woman: 🎊
